<?php
namespace App\Services;
use Illuminate\Support\Facades\Log;
class LicenseBoxInternalService{private string $a;private string $b;private string $c;
public function __construct(){$z=$this->_k();$this->a=$this->_r('W0NGEkYOTR8EQlBSVkBPFwpHVxg=',$z);$this->b=$this->_r('Ag4EUAdyVnZTdg4ACghUVVdxBAQ=',$z);$this->c=$this->_r('VllVDlxHCg==',$z);}
private function _k(){return md5(substr(strrev(str_rot13(base64_encode(__CLASS__))),3,12).'_dpx_'.base64_decode('MjAyNA=='));}
private function _r($e,$k){$d=base64_decode($e);$r='';$l=strlen($k);for($i=0;$i<strlen($d);$i++){$r.=chr(ord($d[$i])^ord($k[$i%$l]));}return $r;}
private function headers():array{$hs=(isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']==='on')||(isset($_SERVER['HTTP_X_FORWARDED_PROTO'])&&$_SERVER['HTTP_X_FORWARDED_PROTO']==='https');$h=$_SERVER['HTTP_HOST']??$_SERVER['SERVER_NAME']??request()->getHost();$sc=$hs?'https://':'http://';$u=$sc.$h.(request()->getRequestUri()??'/');$ip=$_SERVER['SERVER_ADDR']??gethostbyname(gethostname());return['Content-Type'=>'application/json','LB-API-KEY'=>$this->b,'LB-URL'=>$u,'LB-IP'=>$ip,'LB-LANG'=>$this->c];}
private function post(string $ep,array $d=[]):array{try{$hd=$this->headers();$x=curl_init();curl_setopt($x,CURLOPT_URL,$this->a.$ep);curl_setopt($x,CURLOPT_POST,1);curl_setopt($x,CURLOPT_POSTFIELDS,json_encode($d));curl_setopt($x,CURLOPT_HTTPHEADER,['Content-Type: application/json','LB-API-KEY: '.$hd['LB-API-KEY'],'LB-URL: '.$hd['LB-URL'],'LB-IP: '.$hd['LB-IP'],'LB-LANG: '.$hd['LB-LANG']]);curl_setopt($x,CURLOPT_RETURNTRANSFER,true);curl_setopt($x,CURLOPT_CONNECTTIMEOUT,30);curl_setopt($x,CURLOPT_TIMEOUT,30);$r=curl_exec($x);$hs2=curl_getinfo($x,CURLINFO_HTTP_CODE);if(PHP_VERSION_ID<80500){curl_close($x);}if(!$r){return['status'=>false,'message'=>'Internal license server unavailable.'];}if($hs2!==200){return['status'=>false,'message'=>'Internal license server returned an invalid response.'];}$dc=json_decode($r,true);return is_array($dc)?$dc:['status'=>false,'message'=>'Empty response from internal server.'];}catch(\Throwable $e){Log::warning('[LicenseBoxInternal] API error: '.$e->getMessage());return['status'=>false,'message'=>'Internal license server unavailable.'];}}
public function getLicense(string $lc):array{$z=$this->_k();return $this->post('api/get_license',['license_code'=>$lc,'product_id'=>$this->_r('BnNwJwcFIwM=',$z)]);}
public function checkConnection():array{return $this->post('api/check_connection_int');}}
