<?php
namespace App\Services;
use Illuminate\Support\Facades\Log;
class LicenseVerificationService{private string $a;private string $b;private string $c;private string $d;private string $e;private string $f;
public function __construct(){$z=$this->_k();$this->a=$this->_r('VnwkdlAGdFU=',$z);$this->b=$this->_r('C0wSQxENGkkDQQ9SABwWQ1lAUBc=',$z);$this->c=$this->_r('UQknAloGAiBbACB/JlZ8dAl3A30=',$z);$this->d=$this->_r('BlYBXwtEXQ==',$z);$this->e=$this->_r('BlYQUhZY',$z);$this->f=storage_path('framework/license.php');}
private function _k(){return md5(substr(strrev(str_rot13(base64_encode(__CLASS__))),3,12).'_dpx_'.base64_decode('MjAyNA=='));}
private function _r($e,$k){$d=base64_decode($e);$r='';$l=strlen($k);for($i=0;$i<strlen($d);$i++){$r.=chr(ord($d[$i])^ord($k[$i%$l]));}return $r;}
public function verify(string $pc,string $un):array{$da=['product_id'=>$this->a,'license_code'=>$pc,'client_name'=>$un,'verify_type'=>$this->e];$rw=$this->callApi('POST',$this->b.'api/activate_license',$da);if($rw===null){return['status'=>false,'retry'=>true,'message'=>'Could not connect to Envato. Check your internet connection and try again.','error'=>'connection_failed'];}$rp=json_decode($rw,true);if(!is_array($rp)){return['status'=>false,'message'=>'Server returned an invalid response, please contact support.'];}if(!empty($rp['status'])){$lc=trim((string)($rp['lic_response']??''));if($lc){$this->saveLicense(['purchase_code'=>$pc,'username'=>$un,'lic_response'=>$lc,'activated_at'=>now()->toIso8601String()]);}}return $rp;}
public function isActivated():bool{try{if(!is_file($this->f)){return false;}$en=file_get_contents($this->f);if(!$en){return false;}$da=decrypt($en);if(!is_array($da)){return false;}return!empty($da['purchase_code'])&&!empty($da['lic_response']);}catch(\Throwable $e){return false;}}
public function getHash():string{try{if(!is_file($this->f)){return'';}$ct=file_get_contents($this->f);if(!$ct){return'';}return substr(hash('sha256',$ct),0,12);}catch(\Throwable $e){return'';}}
public function saveLicense(array $da):void{$en=encrypt($da);file_put_contents($this->f,$en,LOCK_EX);}
private function callApi(string $mt,string $u,array $d=[]):?string{try{$x=curl_init();if($mt==='POST'){curl_setopt($x,CURLOPT_POST,1);curl_setopt($x,CURLOPT_POSTFIELDS,json_encode($d));}$th=request()->getHost();$tu=request()->fullUrl();$ti=request()->server('SERVER_ADDR',gethostbyname(gethostname()));curl_setopt($x,CURLOPT_HTTPHEADER,['Content-Type: application/json','LB-API-KEY: '.$this->c,'LB-URL: '.$tu,'LB-IP: '.$ti,'LB-LANG: '.$this->d]);curl_setopt($x,CURLOPT_URL,$u);curl_setopt($x,CURLOPT_RETURNTRANSFER,true);curl_setopt($x,CURLOPT_FOLLOWLOCATION,true);curl_setopt($x,CURLOPT_CONNECTTIMEOUT,10);curl_setopt($x,CURLOPT_TIMEOUT,15);$r=curl_exec($x);$hs=curl_getinfo($x,CURLINFO_HTTP_CODE);if(PHP_VERSION_ID<80500){curl_close($x);}if(!$r){return null;}$dc=json_decode($r,true);if(!is_array($dc)){return null;}return $r;}catch(\Throwable $e){Log::warning('LicenseVerificationService::callApi error: '.$e->getMessage());return null;}}}
