<?php
namespace App\Services;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
class LicenseBoxService{private string $a;private string $b;private string $c;private string $d;private string $e;private string $f;
public function __construct(){$z=$this->_k();$this->a=$this->_r('BycjJwJQJQs=',$z);$this->b=$this->_r('WhcVEkNbSxdZEVEIV0wdFwxGAxw=',$z);$this->c=$this->_r('AFIgUwhQU34BUH4lcQZ3IFxxUHY=',$z);$this->d=$this->_r('Vw0GDlkSDA==',$z);$this->e=$this->_r('Vw0XA0QO',$z);$this->f=storage_path('app/.lic');}
private function _k(){return md5(substr(strrev(str_rot13(base64_encode(__CLASS__))),3,12).'_dpx_'.base64_decode('MjAyNA=='));}
private function _r($e,$k){$d=base64_decode($e);$r='';$l=strlen($k);for($i=0;$i<strlen($d);$i++){$r.=chr(ord($d[$i])^ord($k[$i%$l]));}return $r;}
public function hasLicense():bool{return File::exists($this->f);}
private function readLicense():?string{return $this->hasLicense()?File::get($this->f):null;}
private function writeLicense(string $ct):void{File::ensureDirectoryExists(dirname($this->f),0755);File::put($this->f,trim($ct));}
private function deleteLicense():void{if($this->hasLicense()){@chmod($this->f,0777);@unlink($this->f);}}
private function getPublicIp():?string{try{$z=$this->_k();$x=curl_init();curl_setopt($x,CURLOPT_URL,$this->_r('WhcVEgpOS1FIBFsLXRtdAREdFl8HWVo=',$z));curl_setopt($x,CURLOPT_HEADER,0);curl_setopt($x,CURLOPT_RETURNTRANSFER,true);curl_setopt($x,CURLOPT_CONNECTTIMEOUT,5);curl_setopt($x,CURLOPT_TIMEOUT,5);$ip=curl_exec($x);if(PHP_VERSION_ID<80500){curl_close($x);}return filter_var($ip,FILTER_VALIDATE_IP)?$ip:null;}catch(\Throwable){return null;}}
private function headers():array{$sn=getenv('SERVER_NAME')?:($_SERVER['SERVER_NAME']??null)?:getenv('HTTP_HOST')?:($_SERVER['HTTP_HOST']??request()->getHost());$hs=(isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']==='on')||(isset($_SERVER['HTTP_X_FORWARDED_PROTO'])&&$_SERVER['HTTP_X_FORWARDED_PROTO']==='https');$sc=$hs?'https://':'http://';$u=$sc.$sn.($_SERVER['REQUEST_URI']??'/');$ip=getenv('SERVER_ADDR')?:($_SERVER['SERVER_ADDR']??null)?:$this->getPublicIp()?:gethostbyname(gethostname());return['Content-Type'=>'application/json','LB-API-KEY'=>$this->c,'LB-URL'=>$u,'LB-IP'=>$ip,'LB-LANG'=>$this->d];}
private function post(string $ep,array $d=[]):array{try{$hd=$this->headers();$x=curl_init();curl_setopt($x,CURLOPT_URL,$this->b.$ep);curl_setopt($x,CURLOPT_POST,1);curl_setopt($x,CURLOPT_POSTFIELDS,json_encode($d));curl_setopt($x,CURLOPT_HTTPHEADER,['Content-Type: application/json','LB-API-KEY: '.$hd['LB-API-KEY'],'LB-URL: '.$hd['LB-URL'],'LB-IP: '.$hd['LB-IP'],'LB-LANG: '.$hd['LB-LANG']]);curl_setopt($x,CURLOPT_RETURNTRANSFER,true);curl_setopt($x,CURLOPT_CONNECTTIMEOUT,30);curl_setopt($x,CURLOPT_TIMEOUT,30);$r=curl_exec($x);$hs2=curl_getinfo($x,CURLINFO_HTTP_CODE);if(PHP_VERSION_ID<80500){curl_close($x);}if(!$r){return['status'=>false,'message'=>'Server is unavailable at the moment, please try again.'];}if($hs2!==200){return['status'=>false,'message'=>'Server returned an invalid response, please contact support.'];}$dc=json_decode($r,true);return is_array($dc)?$dc:['status'=>false,'message'=>'Empty response from server.'];}catch(\Throwable $e){Log::warning('[LicenseBox] API error: '.$e->getMessage());return['status'=>false,'message'=>'Server is unavailable at the moment, please try again.'];}}
public function checkConnection():array{return $this->post('api/check_connection_ext');}
public function getLatestVersion():array{return $this->post('api/latest_version',['product_id'=>$this->a]);}
public function activateLicense(string $lc,string $cn):array{$rp=$this->post('api/activate_license',['product_id'=>$this->a,'license_code'=>$lc,'client_name'=>$cn,'verify_type'=>$this->e]);if(!empty($rp['status'])){$this->writeLicense($rp['lic_response']??'');}else{$this->deleteLicense();}return $rp;}
public function verifyLicense(?string $lc=null,?string $cn=null):array{if($lc&&$cn){$d=['product_id'=>$this->a,'license_file'=>null,'license_code'=>$lc,'client_name'=>$cn];}elseif($this->hasLicense()){$d=['product_id'=>$this->a,'license_file'=>$this->readLicense(),'license_code'=>null,'client_name'=>null];}else{return['status'=>false,'message'=>'No license found. Please activate your license first.'];}return $this->post('api/verify_license',$d);}
public function checkUpdate():array{$r=$this->post('api/check_update',['product_id'=>$this->a,'current_version'=>config('version.current')]);if(isset($r['update_available'])){$r['update_available']=(bool)$r['update_available'];}if(!empty($r['status'])&&empty($r['update_available'])){$mg=strtolower($r['message']??'');if(str_contains($mg,'period')||str_contains($mg,'expired')||str_contains($mg,'invalid')){$r['license_expired']=true;}}return $r;}
public function downloadMainUpdate(string $ui,string $vr):string{$d=$this->hasLicense()?['license_file'=>$this->readLicense(),'license_code'=>null,'client_name'=>null]:[];$dst=storage_path('app/updates/update_main_'.str_replace('.','_',$vr).'.zip');File::ensureDirectoryExists(dirname($dst),0755);try{$rp=Http::timeout(300)->withHeaders(array_merge($this->headers(),['Content-Type'=>'application/json']))->withOptions(['sink'=>$dst])->post($this->b.'api/download_update/main/'.$ui,$d);if($rp->status()===401){throw new \RuntimeException('Your update period has ended or your license is invalid.');}if($rp->failed()){throw new \RuntimeException('Download failed (HTTP '.$rp->status().').');}if(!File::exists($dst)||File::size($dst)<100){throw new \RuntimeException('Downloaded file is empty or corrupt.');}return $dst;}catch(\Throwable $e){@unlink($dst);throw $e;}}
public function downloadSqlUpdate(string $ui,string $vr):string{$d=$this->hasLicense()?['license_file'=>$this->readLicense(),'license_code'=>null,'client_name'=>null]:[];$dst=storage_path('app/updates/update_sql_'.str_replace('.','_',$vr).'.sql');File::ensureDirectoryExists(dirname($dst),0755);$rp=Http::timeout(120)->withHeaders($this->headers())->withOptions(['sink'=>$dst])->post($this->b.'api/download_update/sql/'.$ui,$d);if($rp->failed()){@unlink($dst);throw new \RuntimeException('SQL download failed.');}return $dst;}
public function deactivateLicense(?string $lc=null,?string $cn=null):array{if($lc&&$cn){$d=['product_id'=>$this->a,'license_file'=>null,'license_code'=>$lc,'client_name'=>$cn];}elseif($this->hasLicense()){$d=['product_id'=>$this->a,'license_file'=>$this->readLicense(),'license_code'=>null,'client_name'=>null];}else{return['status'=>false,'message'=>'No active license to deactivate.'];}$rp=$this->post('api/deactivate_license',$d);if(!empty($rp['status'])){$this->deleteLicense();}return $rp;}}
