import { useEffect, useRef } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { formatDate as formatDateLocale, formatCurrency as formatCurrencyLocale } from '@/utils/localeFormat';
import { useTranslation } from '@/hooks/useTranslation';

interface Props {
    shipment: any;
    settings: any;
    theme?: 'fedex' | 'dhl';
    organization?: any;
    /** URL to open when scanning the QR (e.g. app tracking page) */
    trackingUrl?: string;
    /** Shipment status label (e.g. "Picked Up", "Pending") */
    statusLabel?: string;
    editable?: boolean;
    editableTerms?: string;
    editableFooterNotes?: string;
    onTermsChange?: (value: string) => void;
    onFooterNotesChange?: (value: string) => void;
}

export default function ProInvoiceTemplate({
    shipment,
    settings,
    theme = 'fedex',
    organization,
    trackingUrl: trackingUrlProp,
    statusLabel,
    editable = false,
    editableTerms,
    editableFooterNotes,
    onTermsChange,
    onFooterNotesChange,
}: Props) {
    const { t } = useTranslation();
    const barcodeRef = useRef<SVGSVGElement>(null);
    const trackingNumber = shipment?.tracking_number || '';
    const trackingUrl = trackingUrlProp || (trackingNumber ? `${typeof window !== 'undefined' ? window.location.origin : ''}/tracking?tracking_number=${encodeURIComponent(trackingNumber)}` : '');

    useEffect(() => {
        if (!trackingNumber || !barcodeRef.current) return;
        import('jsbarcode').then((JsBarcode) => {
            try {
                JsBarcode.default(barcodeRef.current!, trackingNumber, {
                    format: 'CODE128',
                    displayValue: true,
                    margin: 2,
                    height: 36,
                    width: 2,
                    lineColor: '#111',
                    fontOptions: 'bold',
                    fontSize: 11,
                });
            } catch (e) {
                console.error('JsBarcode error', e);
            }
        });
    }, [trackingNumber]);
    const taxRate = parseFloat(settings?.tax_rate || 0);
    const taxName = settings?.tax_name || t('invoice.tax');
    const currency = shipment.currency || 'USD';

    // Use DB-stored invoice_number (generated by SequenceService at creation time).
    // Falls back to prefix+id derivation for shipments created before this feature.
    const prefix = settings?.sequence_prefix || 'INV';
    const padding = parseInt(settings?.sequence_padding || 6);
    const invoiceNumber = shipment.invoice_number || `${prefix}-${String(shipment.id).padStart(padding, '0')}`;

    // Helpers - Using locale format utilities
    const formatDate = (dateString: string) => {
        return formatDateLocale(dateString);
    };

    const formatCurrency = (val: any) => {
        return formatCurrencyLocale(val, currency);
    };

    // Extract weight/dimensions from shipment (no hardcode) - stored in kg/cm, convert to display unit
    const pd = shipment?.package_details;
    const pkgs = pd?.packages ?? (Array.isArray(pd) ? pd : pd ? [pd] : []);
    const firstPkg = pkgs[0] ?? (typeof pd === 'object' && pd && !Array.isArray(pd) ? pd : {});
    const summary = pd?.summary ?? {};
    const weightKg = Number(firstPkg?.weight ?? summary?.total_weight ?? pd?.weight ?? 0) || 0;
    const dims = summary?.max_dims ?? firstPkg ?? pd?.dimensions ?? pd ?? {};
    const lengthCm = Number(dims?.length ?? 0) || 0;
    const widthCm = Number(dims?.width ?? 0) || 0;
    const heightCm = Number(dims?.height ?? 0) || 0;
    const weightUnit = settings?.weight_unit || 'kg';
    const dimUnit = settings?.dimension_unit || 'cm';
    const displayWeight = Math.round((weightUnit === 'lb' ? weightKg / 0.453592 : weightKg) * 10000) / 10000;
    const displayLength = Math.round((dimUnit === 'in' ? lengthCm / 2.54 : lengthCm) * 100) / 100;
    const displayWidth = Math.round((dimUnit === 'in' ? widthCm / 2.54 : widthCm) * 100) / 100;
    const displayHeight = Math.round((dimUnit === 'in' ? heightCm / 2.54 : heightCm) * 100) / 100;
    const weightDisplay = weightKg ? `${displayWeight} ${weightUnit}` : '—';
    const dimensionsDisplay = (displayLength && displayWidth && displayHeight) ? `${displayLength}x${displayWidth}x${displayHeight} ${dimUnit}` : '—';
    const surcharges = Math.max(0, Number(shipment.total ?? 0) - Number(shipment.subtotal ?? 0) - Number(shipment.tax ?? 0) + Number(shipment.discount ?? 0));

    // Payment Methods Logic
    const paymentMethods = [];
    if (settings?.stripe_enabled) paymentMethods.push(t('invoice.credit_card_stripe'));
    if (settings?.paypal_enabled) paymentMethods.push(t('invoice.paypal_pro'));
    if (!paymentMethods.length) paymentMethods.push(t('invoice.bank_transfer_cash'));

    return (
        <div className="invoice-container bg-white shadow-lg print:shadow-none min-h-[297mm] w-[210mm] relative text-[#111] font-sans box-border p-0 m-0 overflow-hidden" data-theme={theme}>
            <style>{`
                /* Theme Scopes */
                [data-theme="fedex"] {
                    --brand: #4f46e5; /* Indigo */
                    --accent: #22c55e; /* Green */
                    --dark: #0b1020;
                    --soft: #f4f6ff;
                }
                [data-theme="dhl"] {
                    --brand: #dc2626; /* Red */
                    --accent: #fbbf24; /* Yellow */
                    --dark: #111827;
                    --soft: #fffbeb;
                }

                @media print {
                    .no-print { display: none !important; }
                    body { background: #fff; margin: 0; }
                    .invoice-container { box-shadow: none; margin: 0; width: 100%; height: 100%; }
                }

                /* Typography */
                .font-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }
                
                /* Layout Utils */
                .topbar {
                    background: linear-gradient(90deg, var(--brand), var(--dark));
                    color: #fff;
                    padding: 24px 32px;
                    position: relative;
                    -webkit-print-color-adjust: exact;
                    print-color-adjust: exact;
                }
                .topbar:after {
                    content: "";
                    position: absolute; left: 0; right: 0; bottom: -4px; height: 12px;
                    background: repeating-linear-gradient(
                        90deg,
                        var(--accent) 0px, var(--accent) 20px,
                        rgba(255,255,255,0) 20px, rgba(255,255,255,0) 36px
                    );
                    opacity: 0.9;
                }
            `}</style>

            {/* Header */}
            <div className="topbar">
                <div className="flex justify-between items-start">
                    <div className="flex items-center gap-4">
                        {/* Brand Mark */}
                        <div className="w-[14px] h-[48px] rounded-[4px] bg-[var(--accent)] shadow-[inset_0_0_0_2px_rgba(255,255,255,0.2)] print-color-adjust-exact"></div>
                        <div>
                            <h1 className="text-xl font-bold tracking-tight m-0 text-white">{organization?.name || 'DeprixaPlus'} · {t('invoice.title')}</h1>
                            <div className="text-xs opacity-90 mt-1 text-white">{organization?.tagline || organization?.legal_name || t('invoice.brand_tagline')}</div>
                        </div>
                    </div>

                    <div className="text-right bg-white/10 border border-white/20 px-4 py-3 rounded-lg min-w-[200px]">
                        <div className="text-[10px] font-extrabold uppercase opacity-80 tracking-wider text-white">{t('invoice.invoice_label')}</div>
                        <div className="text-lg font-black mt-1 font-mono text-white">{invoiceNumber}</div>
                        <div className="mt-2 text-[11px] opacity-90 space-y-1 text-white">
                            <div className="flex justify-between gap-4"><span>{t('invoice.date')}:</span> <span className="font-mono font-bold">{formatDate(shipment.created_at)}</span></div>
                            <div className="flex justify-between gap-4"><span>{t('invoice.tracking')}:</span> <span className="font-mono font-bold">{shipment.tracking_number}</span></div>
                            <div className="flex justify-between gap-4">
                                <span>{t('invoice.payment')}:</span>
                                <span className={`uppercase font-bold px-1.5 py-0.5 rounded text-[10px] ${shipment.payment_status === 'paid' ? 'bg-green-500 text-white' : 'bg-amber-500 text-white'}`}>
                                    {shipment.payment_status === 'paid' ? t('invoice.paid') : t('invoice.unpaid')}
                                </span>
                            </div>
                            {statusLabel != null && statusLabel !== '' && (
                                <div className="flex justify-between gap-4">
                                    <span>{t('invoice.shipment')}:</span>
                                    <span className="uppercase font-bold px-1.5 py-0.5 rounded text-[10px] bg-white/20 text-white">
                                        {statusLabel}
                                    </span>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>

            {/* Body - pb-40 reserva espacio para el footer y evita que el QR tape el Total a pagar */}
            <div className="p-8 pb-40">
                {/* 2-Col Grid: Company & Customer */}
                <div className="grid grid-cols-2 gap-6 mb-6">
                    {/* Carrier / Company - datos reales de la organización */}
                    <div className="border border-gray-200 rounded-xl overflow-hidden">
                        <div className="bg-[var(--soft)] px-4 py-2.5 font-extrabold text-[11px] uppercase tracking-wide border-b border-gray-200 flex justify-between print-color-adjust-exact text-[#111]">
                            <span>{t('invoice.company_carrier')}</span>
                            <span className="font-mono opacity-70">{organization?.name ? organization.name.replace(/\s+/g, '').slice(0, 8).toUpperCase() : 'DPX-LOG'}</span>
                        </div>
                        <div className="p-4 text-[13px] leading-snug">
                            <div className="font-bold text-base mb-1">{organization?.legal_name || organization?.name || '—'}</div>
                            {organization?.address && <div>{organization.address}</div>}
                            <div>{[organization?.city, organization?.state, organization?.zip_code, organization?.country].filter(Boolean).join(', ')}</div>
                            {organization?.email && <div className="text-gray-500 mt-2">Email: <span className="font-mono text-black">{organization.email}</span></div>}
                            {organization?.phone && <div className="text-gray-500">Tel: <span className="font-mono text-black">{organization.phone}</span></div>}
                        </div>
                    </div>

                    {/* Customer */}
                    <div className="border border-gray-200 rounded-xl overflow-hidden">
                        <div className="bg-[var(--soft)] px-4 py-2.5 font-extrabold text-[11px] uppercase tracking-wide border-b border-gray-200 flex justify-between print-color-adjust-exact text-[#111]">
                            <span>{t('invoice.customer_bill_to')}</span>
                            <span className="font-mono opacity-70">{shipment.tracking_number || `CUST-${shipment.sender_id}`}</span>
                        </div>
                        <div className="p-4 text-[13px] leading-snug">
                            <div className="font-bold text-base mb-1">{shipment.receiver_details?.name || '—'}</div>
                            <div>{[shipment.receiver_details?.address, shipment.receiver_details?.address_line2, shipment.receiver_details?.city, shipment.receiver_details?.state, shipment.receiver_details?.zip_code, shipment.receiver_details?.country].filter(Boolean).join(', ') || '—'}</div>
                            {shipment.receiver_details?.email && <div className="text-gray-500 mt-1">Email: <span className="font-mono text-black">{shipment.receiver_details.email}</span></div>}
                            <div className="text-gray-500">Tel: <span className="font-mono text-black">{shipment.receiver_details?.phone || '—'}</span></div>
                        </div>
                    </div>
                </div>

                {/* 2-Col Grid: Shipment & Ref */}
                <div className="grid grid-cols-2 gap-6 mb-6">
                    <div className="border border-gray-200 rounded-xl overflow-hidden">
                        <div className="bg-[var(--soft)] px-4 py-2.5 font-extrabold text-[11px] uppercase tracking-wide border-b border-gray-200 flex justify-between print-color-adjust-exact text-[#111]">
                            <span>{t('invoice.shipment_details')}</span>
                            <span className="font-mono opacity-70">{shipment.origin_country_code} &rarr; {shipment.destination_country_code}</span>
                        </div>
                        <div className="p-4 text-[13px] grid grid-cols-2 gap-2">
                            <div><span className="text-gray-500">{t('invoice.service_label')}:</span> <span className="font-bold ml-1">{(shipment as any).service_name ?? ((shipment.service_type ?? '').replace(/^svc_/, '').replace(/_/g, ' ') || '—')}</span></div>
                            <div><span className="text-gray-500">{t('invoice.pieces')}:</span> <span className="font-mono font-bold ml-1">{shipment.packages_count ?? '—'}</span></div>
                            <div>
                                <span className="text-gray-500">{t('invoice.weight')}:</span>
                                <span className="font-mono font-bold ml-1">{weightDisplay}</span>
                            </div>
                            <div>
                                <span className="text-gray-500">{t('invoice.dimensions')}:</span>
                                <span className="font-mono font-bold ml-1">{dimensionsDisplay}</span>
                            </div>
                        </div>
                    </div>

                    <div className="border border-gray-200 rounded-xl overflow-hidden">
                        <div className="bg-[var(--soft)] px-4 py-2.5 font-extrabold text-[11px] uppercase tracking-wide border-b border-gray-200 flex justify-between print-color-adjust-exact text-[#111]">
                            <span>{t('invoice.reference_content')}</span>
                            <span className="font-mono opacity-70">REF: {shipment.external_order_id || shipment.tracking_number || '—'}</span>
                        </div>
                        <div className="p-4 text-[13px]">
                            <div><span className="text-gray-500">{t('invoice.content')}:</span> {(shipment.package_details?.label_content ?? shipment.package_details?.[0]?.content ?? shipment.package_details?.[0]?.content_description ?? (typeof shipment.package_details === 'object' && shipment.package_details && !Array.isArray(shipment.package_details) ? (shipment.package_details?.content_description ?? shipment.package_details?.packages?.[0]?.content_description) : null)) || '—'}</div>
                            <div className="mt-1"><span className="text-gray-500">{t('invoice.declared_value')}:</span> <span className="font-mono font-bold ml-1">{formatCurrency(shipment.package_details?.label_declared_value ?? shipment.package_details?.[0]?.declared_value ?? (shipment.package_details && !Array.isArray(shipment.package_details) ? (shipment.package_details?.summary?.declared_value_total ?? shipment.package_details?.declared_value ?? shipment.package_details?.packages?.[0]?.declared_value) : undefined))}</span></div>
                            <div className="mt-2 text-[10px] italic text-gray-400">{t('invoice.customs_note')}</div>
                        </div>
                    </div>
                </div>

                {/* Table */}
                <table className="w-full border-collapse border border-gray-200 rounded-xl overflow-hidden mb-6">
                    <thead className="bg-gray-900 text-white text-[11px] uppercase print-color-adjust-exact">
                        <tr>
                            <th className="px-4 py-3 text-left w-[40%]">{t('invoice.description')}</th>
                            <th className="px-4 py-3 text-left w-[20%]">{t('invoice.details')}</th>
                            <th className="px-4 py-3 text-right w-[10%]">{t('invoice.qty')}</th>
                            <th className="px-4 py-3 text-right w-[15%]">{t('invoice.unit_price')}</th>
                            <th className="px-4 py-3 text-right w-[15%]">{t('invoice.total')}</th>
                        </tr>
                    </thead>
                    <tbody className="text-[13px]">
                        <tr className="border-b border-gray-100 odd:bg-gray-50 print-color-adjust-exact">
                            <td className="px-4 py-3">
                                <div className="font-bold">
                                    {shipment.service_name ?? ((shipment.service_type ?? '').replace(/^svc_/, '').replace(/_/g, ' ') || '—')}
                                </div>
                                {shipment.service_description && (
                                    <div className="text-xs text-gray-500">{shipment.service_description}</div>
                                )}
                            </td>
                            <td className="px-4 py-3 font-mono text-xs">
                                {(shipment as any).service_name ?? ((shipment.service_type ?? '').replace(/^svc_/, '').replace(/_/g, ' ') || '—')}
                            </td>
                            <td className="px-4 py-3 text-right font-mono">1</td>
                            <td className="px-4 py-3 text-right font-mono">{formatCurrency(shipment.subtotal)}</td>
                            <td className="px-4 py-3 text-right font-mono font-bold">{formatCurrency(shipment.subtotal)}</td>
                        </tr>
                        {/* Tax Row */}
                        <tr className="border-b border-gray-100 odd:bg-gray-50 print-color-adjust-exact">
                            <td className="px-4 py-3">
                                <div className="font-bold">{taxName}</div>
                                <div className="text-xs text-gray-500">{t('invoice.statutory_tax', { percent: taxRate })}</div>
                            </td>
                            <td className="px-4 py-3 font-mono text-xs">
                                {taxRate}% on {formatCurrency(shipment.subtotal)}
                            </td>
                            <td className="px-4 py-3 text-right font-mono">-</td>
                            <td className="px-4 py-3 text-right font-mono">-</td>
                            <td className="px-4 py-3 text-right font-mono">{formatCurrency(shipment.tax)}</td>
                        </tr>
                    </tbody>
                </table>

                {/* Footer Totals & Notes */}
                <div className="flex gap-6 items-start mb-6">
                    <div className="flex-1 border border-dashed border-gray-300 rounded-xl p-3 bg-white">
                        <strong className="text-xs uppercase text-gray-500 block mb-1">{t('invoice.notes_terms')}</strong>
                        {editable && onTermsChange ? (
                            <textarea
                                className="w-full text-[11px] text-gray-600 leading-relaxed min-h-[60px] resize-y border-0 p-0 bg-transparent focus:ring-1 focus:ring-indigo-300 rounded no-print"
                                value={editableTerms ?? settings?.invoice_terms ?? ''}
                                onChange={(e) => onTermsChange(e.target.value)}
                                placeholder={t('invoice.payment_due_placeholder')}
                            />
                        ) : (
                            <p className="text-[11px] text-gray-600 leading-relaxed whitespace-pre-wrap">
                                {settings?.invoice_terms || settings?.footer_notes || t('invoice.delivery_default_terms')}
                            </p>
                        )}
                    </div>

                    <div className="w-[350px] border border-gray-200 rounded-xl overflow-hidden">
                        <div className="flex justify-between px-4 py-2.5 text-[13px] border-b border-gray-200">
                            <span>{t('invoice.subtotal')}</span>
                            <span className="font-mono font-bold">{formatCurrency(shipment.subtotal)}</span>
                        </div>
                        {surcharges > 0 && (
                            <div className="flex justify-between px-4 py-2.5 text-[13px] border-b border-gray-200">
                                <span>{t('invoice.surcharges')}</span>
                                <span className="font-mono">{formatCurrency(surcharges)}</span>
                            </div>
                        )}
                        <div className="flex justify-between px-4 py-2.5 text-[13px] border-b border-gray-200 bg-gray-50">
                            <span>{t('invoice.tax_label', { name: taxName })}</span>
                            <span className="font-mono">{formatCurrency(shipment.tax)}</span>
                        </div>
                        <div className="flex justify-between px-4 py-3 text-[15px] bg-gradient-to-r from-[var(--brand)] to-[var(--dark)] text-white font-bold print-color-adjust-exact">
                            <span>{t('invoice.total_due')}</span>
                            <span className="font-mono">{formatCurrency(shipment.total)}</span>
                        </div>
                    </div>
                </div>

                {/* QR y código de barras - debajo del Total a pagar con espacio */}
                <div className="invoice-qr-tracking-block flex justify-end mt-10 mb-6">
                    <div className="text-right flex flex-col items-end gap-2">
                        {trackingUrl && <QRCodeSVG value={trackingUrl} size={80} level="H" />}
                        <div className="text-[10px] font-bold text-gray-900">{t('invoice.scan_to_track')}</div>
                        {trackingNumber && (
                            <div className="mt-1 flex flex-col items-center">
                                <svg ref={barcodeRef} className="max-w-full h-[44px]" />
                                <div className="text-[9px] font-mono font-bold text-gray-700 mt-0.5">{trackingNumber}</div>
                            </div>
                        )}
                    </div>
                </div>

                {/* Payment Activity / List */}
                {shipment?.payments && Array.isArray(shipment.payments) && shipment.payments.length > 0 && (
                    <div className="mb-6 border border-gray-200 rounded-xl overflow-hidden">
                        <div className="px-4 py-2 bg-gray-50 border-b border-gray-200 font-bold text-[11px] uppercase text-gray-600">
                            {t('invoice.payment_activity')}
                        </div>
                        <table className="w-full text-[11px]">
                            <thead>
                                <tr className="border-b border-gray-100 bg-gray-50/50">
                                    <th className="px-4 py-2 text-left">{t('invoice.date')}</th>
                                    <th className="px-4 py-2 text-left">{t('invoice.method')}</th>
                                    <th className="px-4 py-2 text-right">{t('invoice.amount')}</th>
                                    <th className="px-4 py-2 text-left">{t('invoice.registered_by')}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {shipment.payments.map((p: any) => (
                                    <tr key={p.id} className="border-b border-gray-100">
                                        <td className="px-4 py-2">{formatDate(p.created_at)}</td>
                                        <td className="px-4 py-2 capitalize">{p.method}</td>
                                        <td className="px-4 py-2 text-right font-mono font-semibold">{formatCurrency(p.amount)}</td>
                                        <td className="px-4 py-2 text-gray-600">{p.creator?.name ?? '—'}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}

                {/* Signature - New Feature */}
                {settings?.signature_url && (
                    <div className="mb-6 flex justify-end">
                        <div className="text-center">
                            <img src={settings.signature_url} className="h-16 object-contain mb-1" alt="Signature" />
                            <div className="text-[10px] uppercase font-bold text-gray-400 border-t border-gray-300 pt-1 w-40">{t('invoice.authorized_signature')}</div>
                        </div>
                    </div>
                )}
            </div>

            {/* Sticky Footer */}
            <div className="absolute bottom-0 left-0 right-0 p-8 border-t border-gray-200 flex justify-between items-end">
                <div className="bg-gray-50 border border-gray-200 rounded-xl p-3 w-[60%] print-color-adjust-exact">
                    <div className="font-black text-[11px] uppercase mb-2">{t('invoice.payment_methods')}</div>
                    <div className="flex flex-wrap gap-2">
                        {paymentMethods.map(pm => (
                            <span key={pm} className="px-2 py-1 bg-white border border-gray-200 rounded text-[10px] font-bold text-gray-600 shadow-sm">
                                {pm}
                            </span>
                        ))}
                    </div>
                    {editable && onFooterNotesChange ? (
                        <div className="mt-2">
                            <span className="text-[10px] text-gray-400 block mb-1">{t('invoice.footer_notes')}</span>
                            <textarea
                                className="w-full text-[10px] text-gray-600 min-h-[36px] resize-y border border-gray-200 rounded p-1.5 focus:ring-1 focus:ring-indigo-300 no-print"
                                value={editableFooterNotes ?? settings?.footer_notes ?? ''}
                                onChange={(e) => onFooterNotesChange(e.target.value)}
                                placeholder={t('invoice.thanks')}
                            />
                            <div className="mt-1.5 text-[10px] text-gray-400">
                                {t('invoice.payment_reference')}: <span className="font-mono text-black font-bold">{invoiceNumber}</span>
                            </div>
                        </div>
                    ) : (
                        <div className="mt-2 text-[10px] text-gray-400">
                            {settings?.footer_notes && <span className="block text-gray-600 mb-1">{settings.footer_notes}</span>}
                            {settings?.tax_number && (
                                <span className="block text-gray-500 mb-1">{t('invoice.tax_id', { defaultValue: 'Tax ID' })}: <span className="font-mono font-bold text-gray-700">{settings.tax_number}</span></span>
                            )}
                            {t('invoice.payment_reference')}: <span className="font-mono text-black font-bold">{invoiceNumber}</span>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
