<?php
// *************************************************************************
// *                                                                       *
// * DEPRIXA PLUS - The All-in-One Courier  & Logistics Platform           *
// * Copyright (c) CODDINGPRO. All Rights Reserved                         *
// *                                                                       *
// *************************************************************************

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Adds invoice_number to shipments so every invoice has a permanent,
 * DB-stored reference number that survives soft-deletes and is fully
 * queryable/searchable without computing it client-side.
 *
 * Generated by SequenceService::nextInvoiceNumber() at shipment creation.
 * Nullable to allow backfill of existing shipments without downtime.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('shipments', function (Blueprint $table) {
            // After uuid so it appears near the top of the table schema.
            $table->string('invoice_number', 50)->nullable()->unique()->after('uuid');
        });
    }

    public function down(): void
    {
        Schema::table('shipments', function (Blueprint $table) {
            $table->dropUnique(['invoice_number']);
            $table->dropColumn('invoice_number');
        });
    }
};
